#pragma once

template <class T>
class CProxy_IcvCompilerEvents : public IConnectionPointImpl<T, &__uuidof( _IcvCompilerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
