#pragma once

template <class T>
class CProxy_IMmTradeViewEvents : public IConnectionPointImpl<T, &__uuidof( _IMmTradeViewEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
