VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsIndexWeightAtom"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public IndexSymbol As String
Public ComponentSymbol As String
Public Weight As Double

Public Sub Clear()
    IndexSymbol = ""
    ComponentSymbol = ""
    Weight = BAD_DOUBLE_VALUE
End Sub
