//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EtsEodManager.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDS_STEP_MKT_STRUCTURE          129
#define IDS_STEP_UND_BETA               131
#define IDD_EODSETTINGS                 131
#define IDS_STEP_AVG_VOLUME             132
#define IDS_STEP_IV_BAND                133
#define IDS_STEP_SKEW_KURT              134
#define IDS_STEP_DEFAULT_IV             135
#define IDS_STEP_OPT_CLOSE_PRICE        136
#define IDS_STEP_UND_CLOSE_PRICE        137
#define IDS_STEP_CALC_THEO_PRICE        138
#define IDS_STEP_CALC_WTD_VEGA          139
#define IDD_CONNECTIONS                 140
#define IDS_STEP_OVERALL                140
#define IDD_EODMANAGERVIEW              141
#define IDS_STEP_CALC_COMM_VOLA         141
#define IDD_DBCONNECTION                142
#define IDS_STEP_IDX_FUTURE             142
#define IDS_STEP_COMMODITY              143
#define IDS_STEP_INTEREST               144
#define IDI_TYPE_START                  147
#define IDI_TYPE_END                    148
#define IDI_TYPE_INFO                   149
#define IDI_TYPE_END_WITH_ERRORS        150
#define IDI_ICON1                       151
#define IDI_TYPE                        151
#define IDI_TYPE_WARNING                152
#define IDI_TYPE_INFO1                  153
#define IDI_TYPE_ERROR                  153
#define IDR_POPUPMENU                   156
#define ID_OPEN                         157
#define ID_Menu                         158
#define ID__STOPENDOFDAY                159
#define IDC_APP_ICON                    1000
#define IDC_APP_NAME                    1001
#define IDC_APP_COPYRIGHT               1002
#define IDC_APP_DESC                    1003
#define IDC_APP_VERSION                 1004
#define IDC_APP_COMPONENTS              1006
#define IDC_FG_REPORT                   1007
#define IDC_STEP_AVG_VOLUME             1011
#define IDC_STEP_IV_BAND                1012
#define IDC_STEP_SKEW_KURT              1013
#define IDC_STEP_OPT_CLOSE_PRICE        1015
#define IDC_STEP_UND_CLOSE_PRICE        1016
#define IDC_STEP_CALC_WTD_VEGA          1018
#define IDC_STEP_MKT_STRUCTURE          1019
#define IDC_PARAM_MKT_STRUCTURE_CHECK   1020
#define IDC_RUN_PERIODICALLY            1022
#define IDC_DT_START_TIME               1024
#define IDC_EDIT_DB                     1025
#define IDC_BUTTON_DB_SETUP             1026
#define IDC_PARAM_MKT_STRUCTURE_ACTIVE_ONLY 1026
#define IDC_COMBO_VS_TYPE               1027
#define IDC_PARAM_MKT_STRUCTURE_DEL_OLD_OPT 1027
#define IDC_COMBO_PP_TYPE               1028
#define IDC_EDIT_PP_ACCOUNT             1029
#define IDC_EDIT_PP_PASSWORD            1030
#define IDC_RADIO_PP_PROXY_NONE         1031
#define IDC_RADIO_PP_PROXY_SYSTEM       1032
#define IDC_RADIO_PP_PROXY_CUSTOM       1033
#define IDC_EDIT_PP_PROXY_ADDRESS       1034
#define IDC_EDIT_PP_PROXY_PORT          1035
#define IDC_CHECK_PP_PROXY_AUTH         1036
#define IDC_EDIT_PP_PROXY_PASSWORD      1037
#define IDC_EDIT_PP_PROXY_LOGIN         1038
#define IDC_EDIT_IV_ACCOUNT             1039
#define IDC_EDIT_IV_PASSWORD            1040
#define IDC_RADIO_IV_PROXY_NONE         1041
#define IDC_RADIO_IV_PROXY_SYSTEM       1042
#define IDC_RADIO_IV_PROXY_CUSTOM       1043
#define IDC_EDIT_IV_PROXY_ADDRESS       1044
#define IDC_EDIT_IV_PROXY_PORT          1045
#define IDC_CHECK_IV_PROXY_AUTH         1046
#define IDC_EDIT_IV_PROXY_PASSWORD      1047
#define IDC_EDIT_IV_PROXY_LOGIN         1048
#define IDC_EDIT_IV_ADDRESS             1049
#define IDC_STATIC_PP_TYPE              1050
#define IDC_STATIC_PP_ACCOUNT           1051
#define IDC_STATIC_PP_PASSWORD          1052
#define IDC_STATIC_PP_PROXY             1053
#define IDC_STATIC_PP_PROXY_ADDRESS     1054
#define IDC_STATIC_PP_PROXY_PORT        1055
#define IDC_STATIC_PP_PROXY_LOGIN       1056
#define IDC_STATIC_PP_PROXY_PASSWORD    1057
#define IDC_STATIC_VS_TYPE              1058
#define IDC_STATIC_DB                   1059
#define IDC_STATIC_VS                   1060
#define IDC_STATIC_PP                   1061
#define IDC_STATIC_IV                   1062
#define IDC_STATIC_IV_ADDRESS           1063
#define IDC_STATIC_IV_ACCOUNT           1064
#define IDC_STATIC_IV_PASSWORD          1065
#define IDC_STATIC_IV_PROXY             1066
#define IDC_STATIC_IV_PROXY_ADDRESS     1067
#define IDC_STATIC_IV_PROXY_PORT        1068
#define IDC_STATIC_IV_PROXY_LOGIN       1069
#define IDC_STATIC_IV_PROXY_PASSWORD    1070
#define IDC_COMBO_SERVER                1071
#define IDC_CHECK_NT_SECURITY           1072
#define IDC_EDIT_USERNAME               1073
#define IDC_EDIT_PASSWORD               1074
#define IDC_COMBO_DATABASE              1075
#define IDC_STATIC_USERNAME             1077
#define IDC_STATIC_PASSWORD             1078
#define IDC_PARAM_OPT_CLOSE_PRICE_IV    1079
#define IDC_PARAM_OPT_CLOSE_PRICE_PP    1080
#define IDC_BUTTON_SYS_INFO             1080
#define IDC_COMBO_CALC_MODEL            1081
#define IDC_PARAM_UND_CLOSE_PRICE_IV    1082
#define IDC_PARAM_UND_CLOSE_PRICE_PP    1083
#define IDC_COMBO_LOG_LEVELS            1084
#define IDC_EDIT_LOG_HISTORY            1085
#define IDC_CHECK1                      1087
#define IDC_CHK_UPDATEUND               1087
#define IDC_CHK_UPDATEOPTIONS           1088
#define IDC_CHK_FILTERDIVIDENDS         1089
#define IDC_CHECK3                      1090
#define IDC_CHK_LOADOPTIONS             1090
#define IDC_STEP_IDX_FUTURE             1093
#define IDC_STEP_IDXFUT_PRICES_COMBO    1094
#define ID_OPTIONS_SETTINGS             32771
#define ID_OPTIONS_CONNECTIONS          32772
#define ID_FILE_START_EOD               32773
#define ID_FILE_STOP_EOD                32774
#define ID_VIEW_EXPAND_ALL              32777
#define ID_VIEW_COLLAPSE_ALL            32778
#define ID_VIEW_COLLAPSE_ALL2           32779
#define ID_VIEW_SHOW_COLOR_CODES        32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
