//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IVAnalyzer.rc
//
#define IDC_START_STRUCTURE             3
#define IDAPPLY                         3
#define ID_REFRESH                      3
#define IDC_STOP_STRUCTURE              4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IVANALYZER_DIALOG           102
#define IDS_YAXIS_TITLE                 102
#define IDR_IVANALYZER                  103
#define IDS_TIME_SKEW_TITLE             103
#define IDD_APP_BAR                     103
#define IDS_STRIKE_SKEW_TITLE           104
#define IDR_MAINFRAME                   128
#define IDD_CHART                       130
#define IDD_MARKET_STRUCTURE            131
#define IDD_DIALOG1                     134
#define IDR_MAIN_TOOLBAR                135
#define IDR_LOGO                        138
#define IDR_STRIKE_SKEW                 142
#define IDR_WINDOW_TOOLBAR              144
#define IDR_SERVICES_TOOLBAR            144
#define IDB_MONTHS                      146
#define IDR_MAIN_MENU                   147
#define IDD_INFO_BAR                    148
#define IDB_BITMAP1                     150
#define IDI_BAR                         151
#define IDR_MAIN_ACC                    152
#define IDD_VOLA_MANAGEMENT_DIALOG      153
#define IDD_SPLASH                      154
#define IDB_SPLASH                      155
#define IDR_SYMBOL_TOOLBAR              159
#define IDD_VOLA_EDIT_DIALOG            162
#define IDD_OPTIONS                     163
#define IDD_DIALOG2                     164
#define IDR_WINDOW_POPUP                170
#define IDR_POPUP_TOOLBAR               170
#define IDR_SERVICE_TOOLBAR             172
#define IDD_INTEREST_RATES              174
#define IDR_INTERESTRATE                178
#define IDR_TOOLBAR_IR                  179
#define IDD_MKT_STRUCTURE               189
#define IDR_SPLASH                      194
#define IDR_LOGO_GIF                    203
#define IDB_TB_IMAGES                   205
#define IDB_CHARTS_IMAGES               208
#define IDB_WNDS_IMAGES                 209
#define IDB_SERVICES_IMAGES             210
#define IDB_BAR_ICON                    214
#define IDI_IV_APP                      217
#define IDR_SYSMENU_TOOLBAR             218
#define IDD_VM_STRIKE_DIALOG            220
#define IDD_VM_DELTA_DIALOG             221
#define IDD_VM_MONEYNESS_DIALOG         222
#define IDD_VM_STD_DIALOG               223
#define IDR_IVMANAGER                   223
#define IDD_ADD_SYMBOL                  224
#define IDD_LICENSE                     228
#define IDD_VM_SYMBOL_GROUPS            229
#define IDD_VM_GROUP_STRUCT             230
#define IDD_VM_GROUP_NAME               231
#define IDD_VM_RULE                     232
#define IDD_VM_RULES                    234
#define IDD_REMOVE_SYMBOL               235
#define IDD_VM_SURFACE_ADD_DLG          237
#define IDR_VM_GRID_MENU                239
#define IDR_VM_MAIN_MENU                240
#define IDD_VM_SURFACE_OPEN_DLG         241
#define IDB_VM_RULE_NEW                 242
#define IDB_VM_RULE_EDIT                243
#define IDB_VM_RULE_DEL                 244
#define IDI_VMR_EDIT                    245
#define IDI_VMR_NEW                     246
#define IDI_VMR_DEL                     247
#define IDD_VM_NEXT_DAY_SURFACE_DLG     248
#define IDD_OPT_CONNECTION              249
#define IDD_OPT_SKEW                    250
#define IDI_DQ_PAR                      252
#define IDD_DUALQUAD_PAR                253
#define IDD_ICON_BAR                    262
#define IDR_ICON_GIF                    264
#define IDR_GIF1                        265
#define IDR_LOGO_IVRM_GIF               265
#define IDR_GIF2                        266
#define IDR_IVRM_LOGO_GIF               266
#define IDC_SYMBOL                      1001
#define IDI_SKEW                        1001
#define IDC_TIME_SKEW                   1003
#define IDC_OPTION_PROGRESS             1003
#define IDC_STOCK_PROGRESS              1004
#define IDC_TS_CHART                    1004
#define IDC_ERRORS                      1005
#define IDC_STATUS_INFO                 1005
#define IDC_STOCK_INFO                  1006
#define IDC_STOCK_INFO2                 1007
#define IDC_MONTHES                     1007
#define IDC_SHOW_STRIKE                 1008
#define IDC_REFRESH                     1009
#define IDC_STOP                        1010
#define IDC_LOGO                        1014
#define IDC_INFO                        1015
#define IDC_SYMBOLS                     1017
#define IDC_ABS_STRIKE                  1022
#define IDC_MON_STRIKE                  1023
#define IDC_STRIKE_STYLE                1023
#define IDC_DLT_STRIKE                  1024
#define IDC_UPDATE                      1024
#define IDC_STD_STRIKE                  1025
#define IDC_RESTORE                     1025
#define IDC_TOIMPLIED                   1026
#define IDC_UPDATE_RULE                 1026
#define IDC_SKEW_DELTA                  1027
#define IDC_ACTIVE_SURFACE_ADD          1027
#define IDC_TO_SPOT                     1027
#define IDC_NEW_RULE                    1027
#define IDC_BASE_POINT                  1028
#define IDC_CUR_VOLA                    1028
#define IDC_ACTIVE_SURFACE_REMOVE       1028
#define IDC_DELETE_RULE                 1028
#define IDC_NEW_VOLA                    1029
#define IDC_HIST_SIM                    1029
#define IDC_ACTIVE_SURFACE_MODIFY       1029
#define IDC_DUALQUADR_PAR               1029
#define IDC_CUR_PRICE                   1030
#define IDC_HIST_IV                     1030
#define IDC_NEW_PRICE                   1031
#define IDC_NEW_STRIKE                  1032
#define IDC_CUR_STRIKE                  1033
#define IDC_SIM_HIST                    1033
#define IDC_CONNECTION                  1034
#define IDC_SETUP_CONNECTION            1035
#define IDC_PRICE_ACCOUNT               1036
#define IDC_PRICE_PASSWORD              1037
#define IDC_IV_ACCOUNT                  1038
#define IDC_IV_PASSWORD                 1039
#define IDC_USE_PROXY                   1040
#define IDC_IV_URL                      1041
#define IDC_USE_PROXY2                  1041
#define IDC_PROXY_ADDR                  1042
#define IDC_PROXY_PORT                  1043
#define IDC_TENOR                       1044
#define IDC_PROXY_ADDR2                 1044
#define IDC_VOLA_MGMT                   1045
#define IDC_PROXY_PORT2                 1045
#define IDC_IV_PROXY_ACCOUNT            1046
#define IDC_IV_PROXY_PASSWORD           1047
#define IDC_VSFLEXGRIDADO1              1050
#define IDC_GRID                        1050
#define IDC_HAND_PRE_WIN2K              1051
#define IDC_CAPTION                     1057
#define IDC_LOG                         1058
#define IDC_CALL                        1060
#define IDC_PRODUCT_INFO                1061
#define IDC_PUT                         1062
#define IDC_COPYRIGHT                   1062
#define IDC_OTM                         1063
#define IDC_LOGO_GIF                    1065
#define IDC_SPLASH_PICTURE              1067
#define IDC_VM_CALL                     1068
#define IDC_VM_PUT                      1069
#define IDC_STRIKE_MODE                 1073
#define IDC_ADD_SYMBOL                  1074
#define IDC_NEW_SYMBOL                  1075
#define IDC_PRODUCT_ID                  1077
#define IDC_LICENSE_KEY                 1078
#define IDC_LIST_GROUPS                 1081
#define IDC_BUTTON_NEW                  1082
#define IDC_LIST_ALL                    1083
#define IDC_BUTTON_DELETE               1084
#define IDC_LIST_SEL                    1084
#define IDC_BUTTON_TO                   1085
#define IDC_BUTTON_FROM                 1086
#define IDC_PROMPT                      1086
#define IDC_VALUE                       1087
#define IDC_COMBO_TYPE                  1088
#define IDC_TYPE_TITLE                  1089
#define IDC_INCREMENT                   1090
#define IDC_CALL_SHIFT                  1091
#define IDC_PUT_SHIFT                   1092
#define IDC_ACCELERATOR                 1093
#define IDC_FACTOR                      1094
#define IDC_HI_VOLY                     1095
#define IDC_UNDERLINE_PRICE             1095
#define IDC_LO_VOLY                     1096
#define IDC_ATM_VOLATILITY              1096
#define IDC_SLIDER_FACTOR               1097
#define IDC_CHECK_DEFAULT               1098
#define IDC_LO_VOLATILITY               1098
#define IDC_LIST_ITEMS                  1099
#define IDC_HI_VOLATILITY               1099
#define IDC_COMBO_CURRENT_RULE          1102
#define IDC_COMBO_ACTIVE_SURFACE        1103
#define IDC_VOLA_CALL                   1104
#define IDC_VOLA                        1104
#define IDC_VOLA_PUT                    1105
#define IDC_VOLA_UPDATE                 1106
#define IDC_VOLA_RESTORE                1107
#define IDC_VOLA_REGENERATE             1108
#define IDC_LIST_RULES                  1108
#define IDC_VOLA_REGENERATE2            1109
#define IDC_VOLA_CLEAR                  1109
#define IDC_NAME_EDIT                   1110
#define IDC_VOLA_FITTOIMPLIED           1110
#define IDC_RULE_COMBO                  1111
#define IDC_RULE_EDIT_BUTTON            1112
#define IDC_BUTTON_MODIFY               1113
#define IDC_CALL_SHIFT_TITLE            1114
#define IDC_PUT_SHIFT_TITLE             1115
#define IDC_PRICE_OVERRIDE_CHECK        1116
#define IDC_DISCRETE_ACCEL_CHECK        1117
#define IDC_UNDERLINE_PRICE_TITLE       1118
#define IDC_CHART_ALL                   1119
#define IDC_CHART_NOT5                  1120
#define IDC_CHART_RANGES                1121
#define IDC_CHATR_FROM                  1122
#define IDC_CHATR_TO                    1123
#define IDC_CHECK_RANGE                 1124
#define IDC_FLAT_OUT_RANGE              1125
#define IDC_FLAT_WHEN_NO_BID            1126
#define IDC_COMBO_SYMBOLS               1127
#define IDC_SURFACE_NAME                1128
#define IDC_DEFAULT_SURFACE             1129
#define IDC_UPPER_LINE                  1130
#define IDC_LIST_SURFACE                1131
#define IDC_STATIC_RULE                 1132
#define IDC_STATIC_IF                   1133
#define IDC_STATIC_LV                   1134
#define IDC_STATIC_LVP                  1135
#define IDC_STATIC_HV                   1136
#define IDC_STATIC_HVP                  1137
#define IDC_SURFACE                     1138
#define IDC_STATIC_UP                   1139
#define IDC_STATIC_SA                   1140
#define IDC_PROVIDERTYPE                1141
#define IDC_SMILE_ACCELERATOR_TITLE     1142
#define IDC_STATIC_PROXYACC             1145
#define IDC_STATIC_PROXYPASS            1146
#define IDC_CHECK_PROXYAUTH             1147
#define IDC_MODEL_BINOMINAL             1148
#define IDC_MODEL_OPT_BINOMINAL         1149
#define IDC_DUALQUADP_GRID              1149
#define IDC_MODEL_VSKLOG                1150
#define IDC_ICON_GIF                    1150
#define ID_FILE_EXIT                    32771
#define ID_BUTTON32774                  32774
#define ID_TIME_SKEW                    32775
#define ID_UPDATE_STRUCTURE             32776
#define ID_BLANK                        32786
#define ID_WINDOW_TILE                  32788
#define ID_STRIKE_SKEW                  32791
#define ID_WINDOW                       32792
#define ID_STRIKE_SKEW_ALL              32792
#define ID_STRIKE_SKEW_SHOW_ALL         32793
#define ID_OPTIONS                      32797
#define ID_MAIN_ALWAYSONTOP             32798
#define ID_APPBAR_ALWAYSONTOP           32798
#define ID_APPBAR_AUTOHIDE              32799
#define ID_STRUCTURE_VOLA               32800
#define ID_STRUCTURE                    32801
#define ID_WINDOW_CYCLE_ARRANGE         32802
#define ID_WINDOW_CLOSEALL              32803
#define ID_GO                           32804
#define ID_SELECT_SYMBOL                32805
#define ID_BUTTON32805                  32806
#define ID_CANCEL_SYMBOL                32807
#define ID_SERVICE_BTN                  32811
#define ID_SERVICE_INTERESTRATES        32812
#define ID_SERVICE_IMPORTALL            32814
#define ID_SERVICE_CURRENTSYMBOL        32815
#define ID_BUTTON32816                  32816
#define ID_IR_ADD                       32817
#define ID_IR_EDIT                      32818
#define ID_IR_DELETE                    32819
#define IDS_MSG_SURFACE_SAVE            32820
#define ID_IR_ADD_t                     32823
#define ID_IR_EDIT_t                    32824
#define ID_CHARTS                       32826
#define ID_ADVERTIZING                  32827
#define ID_STATUS                       32828
#define ID_ADD_NEW_SYMBOL               32834
#define ID_SYMBOL_GROUPS                32836
#define ID_RULES                        32837
#define ID_ADD_SYMBOL                   32838
#define ID_REMOVE_SYMBOL                32838
#define IDC_VM_MAKE_BASE_POINT          32841
#define IDC_VM_MAKE_COMOMON_POINT       32842
#define IDC_VM_SURFACE_NEW              32844
#define IDC_VM_SURFACE_DELETE           32845
#define IDC_VM_SURFACE_OPEN             32846
#define IDC_VM_SURFACE_EDIT             32847
#define IDC_VM_VIEW_GENERATION_OPTIONS  32848
#define IDC_VM_SURFACE_SET_AS_DEFAULT   32849
#define ID_NEXTDAYSURFACE               32850
#define IDC_VM_SURFACE_NEXTDAY          32851
#define IDC_VM_VIEW_ALWAYSONTOP         32852
#define IDC_VM_VIEW_SHOWALL             32853
#define IDC_VM_SURFACE_SAVEAS           32854
#define ID_SERVICE_GENDEFVOLA           32855
#define IDC_VM_SELECT_ALL_EXP           32856
#define ID_APP_HELP                     32857
#define ID_STRIKE_SKEW_FIRST            33000
#define ID_STRIKE_SKEW_LAST             34000
#define ERR_IDS_HTTP_INTERNAL           40000
#define ERR_IDS_HTTP_NOT_FOUND          40001
#define ERR_IDS_IV_CANNOT_LOGIN         40002
#define ERR_IDS_IV_ACCESS_DENIED        40003
#define ERR_IDS_IV_OLEDB_TIMEOUT        40004
#define ERR_IDS_IV_TIMEOUT              40005
#define ERR_IDS_IV_OLEDB                40006
#define ERR_IDS_IV_ERROR                40007
#define ERR_IDS_IV_MD5                  40008
#define ERR_IDS_HTTP_ERROR              40009
#define ERR_IDS_NO_PROXY_SETTINGS       40010
#define ERR_IDS_IV_COMMON_PREFIX        40011
#define ERR_IDS_UNEXPECTED              40012
#define IDS_SB_STATUS                   57651
#define IDS_READY                       57651
#define IDS_ADV_DEFAULT                 57652
#define IDS_EXPIRED                     57653
#define IDS_NOT_LICENSED                57654
#define IDS_INTERNET_AGENT              57655
#define IDS_UPDATING_ACTIVE_SYMBOL      57656
#define IDS_MKTSTRUCTURE_GOTDATA        57657
#define IDS_MKTSTRUCTURE_GOTOPTION      57658
#define IDS_MKTSTRUCTURE_ERR_GETDATA    57659
#define IDS_MKTSTRUCTURE_ERROR          57660
#define IDS_MKTSTRUCTURE_INITDATA       57661
#define IDS_MKTSTRUCTURE_CONNECTING     57662
#define IDS_MKTSTRUCTURE_REQUESTING     57663
#define IDS_MKTSTRUCTURE_ERR_NOSTOCKS   57664
#define IDS_MKTSTRUCTURE_CANCELED       57665
#define IDS_MKTSTRUCTURE_GOT            57666
#define IDS_MKTSTRUCTURE_DONE           57667
#define IDS_MKTSTRUCTURE_GOTYELD        57668
#define IDS_CHART_LOGO                  57669
#define IDS_ERROR_WRONGRANGE            57670
#define IDS_ERROR_WRONG_LBOUND          57671
#define IDS_ERROR_WRONG_UBOUND          57672

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        267
#define _APS_NEXT_COMMAND_VALUE         32859
#define _APS_NEXT_CONTROL_VALUE         1151
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
