#ifndef __UI_CMD_DEFS_H__
#define __UI_CMD_DEFS_H__

#define	WM_ICON_NOTIFY				WM_USER + 10
#define WM_HOST_STATISTIC_UPDATE	WM_USER + 11
#define WM_HOST_SETTINGS_UPDATE		WM_USER + 12
#define WM_REFRESH_PROPSHEET		WM_USER + 13
#define WM_TRANSPORT_SERVICE_ERROR	WM_USER + 14
#define WM_TRANSPORT_SERVICE_STATUS	WM_USER + 15

#define RT_STATUS_ONLINE			1000
#define RT_STATUS_OFFLINE			1001

#define TRANSPORT_DISABLED			1002



#endif //__UI_CMD_DEFS_H__