/*PREPARATIONS FOR ERROR HANDLING*/
SET NOCOUNT ON
GO
IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE id=OBJECT_ID('tempdb..#tmpErrors')) DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
/*SCRIPTS MAIN SECTION*/
BEGIN TRANSACTION
GO
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO

	delete from TradeLog
	delete from Trade
	delete from TntCard
	delete from OrderExec
	delete from [Order]
	delete from TraderContract
	delete from Trader
	delete from Strategy

    exec usp_TraderContractStrategy_Import 'US8100', 'ABT', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'ABXA', 'AMID09', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'AMGN', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'AVE', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'AZN', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'BMY', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'DRG', 'DRG', 1
    exec usp_TraderContractStrategy_Import 'US8100', 'FRX', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'GSK', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'HOV', 'AMID09', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'IVX', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'JNJ', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'KG', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'LLY', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'MDY', 'AMID09', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'MHS', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'MID', 'AMID09', 1
    exec usp_TraderContractStrategy_Import 'US8100', 'MRK', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'PFE', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'SGP', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'SPX', 'ASPX09', 1
    exec usp_TraderContractStrategy_Import 'US8100', 'WYE', 'DRG', 2
    exec usp_TraderContractStrategy_Import 'US8100', 'XAU', 'XAU', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'ADI', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'ALTR', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'AMAT', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'AMD', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'AMKR', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'AMZN', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'ATML', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'AXP', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'BRCM', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'CKFR', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'CVX', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'DCLK', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'DD', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'DIA', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'DIS', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'DOW', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'DRG', 'DRGBW1', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'EBAY', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'EK', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'ELNK', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'GE', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'GIN', 'GIN', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'GM', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'IACI', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'IBM', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'INTC', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'IP', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'JNJ', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'KLAC', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'KO', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'LLTC', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'LSCC', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'LSI', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MCD', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MHS', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MMM', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MNST', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MNX', 'MNX', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'MO', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MOT', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MRK', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MU', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'MXIM', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'NDX', 'MNX', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'NSM', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'NVLS', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'OVER', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'PG', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'PPH', 'DRGBW1', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'RNWK', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'S', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'SNDK', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'SOX', 'SOXSPX', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'SPX', 'SPXPS1112', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'SPY', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'STM', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'T', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'TER', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'TSM', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'TXN', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'VTSS', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'XLNX', 'SOXSPX', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'XMI', 'XMI', 1
    exec usp_TraderContractStrategy_Import 'US8101', 'XOM', 'XMI', 2
    exec usp_TraderContractStrategy_Import 'US8101', 'YHOO', 'GIN', 2
    exec usp_TraderContractStrategy_Import 'US8102', 'JHF', 'XLF', 2
    exec usp_TraderContractStrategy_Import 'US8102', 'JNS', 'XLF', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'AGY', 'AGY', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'AMAT', 'AMAT', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'AMCC', 'AMCC', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'AMZN', 'AMZN', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'AWE', 'AWE', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'AXP', 'AXP', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'BAC', 'BAC', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'BBY', 'BBY', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'BGEN', 'BGEN', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'BRCM', 'BRCM', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'CHK', 'CHK', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'CKFR', 'CKFR', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'CSCO', 'CSCO', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DE', 'DE', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DELL', 'DELL', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DIA', 'DIA', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DIS', 'DIS', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DLM', 'HNZ', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DNA', 'DNA', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'DT', 'DT', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'EBAY', 'EBAY', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'EMR', 'EMR', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'EP', 'EP', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'ERTS', 'ERTS', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'FAST', 'FAST', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'FL', 'FL', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'FLEX', 'FLEX', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'FOX', 'FOX', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'GDT', 'GDT', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'GE', 'GE', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'GLW', 'GLW', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'HNZ', 'HNZ', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'HPQ', 'HPQ', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'IACI', 'IACI', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'INTC', 'INTC', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'INTU', 'INTU', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'IVGN', 'IVGN', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'IVX', 'IVX', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'KLAC', 'KLAC', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'KO', 'KO', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'MAS', 'MAS', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'MBI', 'MBI', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'MEDI', 'MEDI', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'MLNM', 'MLNM', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'MWD', 'MWD', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'NEM', 'NEM', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'NVLS', 'NVLS', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'PAYX', 'PAYX', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'PTEN', 'PTEN', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'PVN', 'PVN', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'QCOM', 'QCOM', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'RTN', 'RTN', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'SCRI', 'SCRI', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'SMH', 'SMH', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'SOV', 'SOV', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'SUNW', 'SUNW', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'TMO', 'TMO', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'TYC', 'TYC', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'UTX', 'UTX', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'VIA/B', 'VIA', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'WWCA', 'WWCA', 2
    exec usp_TraderContractStrategy_Import 'US8103', 'XL', 'XL', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'ACS', 'ACS', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'ADLAC', 'ADLAC', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'ADPT', 'ADPT', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'AIG', 'AIG', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'AKZOY', 'AKZOY', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'ALXN', 'ALXN', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'AMMD', 'AMMD', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'AXP', 'AXP', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'BMET', 'BMET', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'BOW', 'BOW', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CAL', 'CAL', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CBH', 'CBH', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CEPH', 'CEPH', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CERN', 'CERN', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CFC', 'CFC', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CI', 'CI', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CL', 'CL', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'CMCSK', 'CMCSK', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'DCX', 'DCX', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'DD', 'DD', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'DELL', 'FNM', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'DPH', 'DPH', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'DVA', 'DVA', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'EMC', 'EMC', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'FCX', 'FCX', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'FDX', 'FDX', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'FNM', 'FNM', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'FRE', 'FRE', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'GAS', 'GAS', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'GM', 'GM', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'GNTA', 'GNTA', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'GP', 'GP', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'GSK', 'GSK', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'HAL', 'HAL', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'HLTH', 'HLTH', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'HON', 'HON', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'ICOS', 'ICOS', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'IP', 'IP', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'JPM', 'JPM', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'KG', 'KG', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'KSS', 'KSS', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'L', 'L', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'LAMR', 'LAMR', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'LLY', 'LLY', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'LPNT', 'LPNT', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'LYO', 'LYO', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MER', 'MER', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MHS', 'MRK', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MIRKQ', 'MIR', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MO', 'MO', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MSFT', 'MSFTdiv', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MU', 'MU', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'MUR', 'MUR', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'NATI', 'NATI', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'NAV', 'NAV', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'NWAC', 'NWAC', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'NWS', 'NWS', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'PCAR', 'PCAR', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'PFE', 'LLY', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'RBK', 'RBK', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'RFMD', 'RFMD', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'RJR', 'RJR', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'S', 'S', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'SFD', 'SFD', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'SGP', 'SGP', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'SU', 'SU', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'SWY', 'SWY', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'TE', 'TE', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'TOY', 'TOY', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'USG', 'USG', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'VC', 'VC', 2
    exec usp_TraderContractStrategy_Import 'US8104', 'VZ', 'VZ', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'ABX', 'ABX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'ADRX', 'ADRX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'AMR', 'AMR', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'AMX', 'AMX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'AMZN', 'AMZN', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'BP', 'BP', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'C', 'C', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'CCU', 'CCU', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'COP', 'COP', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'CVC', 'CVC', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'CZN', 'CZN', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'DDS', 'DDS', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'DGX', 'DGX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'DIS', 'DIS', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'DISH', 'DISH', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'DPH', 'DPH', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'DUK', 'DUKRC', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'EDS', 'EDS', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'EIX', 'EIX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'EMR', 'EMR', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'FLEX', 'FLEX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'FON', 'FON', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'G', 'G', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'GM', 'GM', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'GT', 'GT', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'HBC', 'HI', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'HLTH', 'HLTH', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'IDPH', 'IDPH', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'IPG', 'IPG', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'JPM', 'JPM', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'MEDI', 'MEDI', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'MHS', 'MRK', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'MMM', 'MMM', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'MO', 'MO', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'MRK', 'MRK', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'MU', 'MU', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'NTIQ', 'NTIQ', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'NWS', 'NWS', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'NXTL', 'NXTL', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'ORCL', 'ORCL', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'PFE', 'PFE', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'SGP', 'SGP', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'TGT', 'TGT', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'TMX', 'TMX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'UPS', 'UPS', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'USM', 'USM', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'VRTS', 'VRTS', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'VZ', 'VZ', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'XRX', 'XRX', 2
    exec usp_TraderContractStrategy_Import 'US8105', 'YHOO', 'YHOO', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'AXP', 'Close01', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'DELL', 'DELL', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'ENE', 'Spec04', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'HAL', 'HAL', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'ITWO', 'ITWO', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'JDSU', 'JDSU', 2
    exec usp_TraderContractStrategy_Import 'US8106', 'KO', 'Close01', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ACF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ACI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ACS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ACXM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ADTN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ADVP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ADVS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AEOS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AFC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AFCI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AFG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AGE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AHG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AJG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AKS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ALB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ALE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ALEX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ALK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AMB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AME', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AMH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ANF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AOT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'APPB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ARG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ARM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ARW', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ASBC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ASCL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ATG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ATML', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ATVI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AVCT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'AVT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BCO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BDG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BEC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BER', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BGP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BID', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BJ', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BKH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BKS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BLC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BNK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BOBE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BOH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BOW', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BRL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BRO', 'Del-Pre-', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BSG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BTH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BTU', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'BWA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CAKE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CAM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CBB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CBH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CBRL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CBSS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CBT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CCMP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CDN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CDWC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CECO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CEN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CEY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CHD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CHRW', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CHS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CKFR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CLE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CLI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CMH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CMOS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CNB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CNF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'COH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'COMS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CPRT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CPS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CREE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CRL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CRS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CSGS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CSL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CTV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CVD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CVH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CYH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CYMI', 'CYMI', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CYN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CYT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'CYTC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DBD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DCI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DHI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DIA', 'DJXDIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DJX', 'DJXDIA', 1
    exec usp_TraderContractStrategy_Import 'US8107', 'DL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DLTR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DNB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DPL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DQE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DSS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DST', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'DY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EAGL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EAS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EAT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EDMC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ELY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EMMS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ENR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EQT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ESA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ESRX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ESV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ET', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ETM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EW', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EXPD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'EYE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FAF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FAST', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FBN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FCS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FHCC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FIC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FLS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FMC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FMER', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FNF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FOE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FSS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FST', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'FTI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GBBK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GGG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GILD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GLT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GMT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GNTX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GPT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GRP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GTK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GVA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'GXP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HCC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HHS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HIB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HMN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HNI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HNT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HPT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HRL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HRS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HSC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HSIC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HSP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'HUB/B', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IBC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ICBC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ICN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ICST', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IDA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IDPH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IDTI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IFIN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IGL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ILA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IMN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'INFS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IRF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ISCA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ISIL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ISSX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IT/B', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ITG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ITWO', 'ITWO', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ITWOE', 'ITWO', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'IVX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'JBHT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'JEC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'JKHY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KEA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KELYA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KEM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KFT', 'KFT', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KFY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KKD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KMT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'KMX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LAB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LANC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LDG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LEA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LEE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LEN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LFB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LGTO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LLL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LNCR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LNT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LPNT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LRCX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LRY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LSCC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LTXX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LUK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LYO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'LZ', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MACR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MAN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MBG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MCDTA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MCHP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MCRL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MDU', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MDY', 'MDYFUT', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MEG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MENT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MHK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MIK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MLHR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MLM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MLNM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MNY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MODI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MPS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MRBK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MTB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MTX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MUR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MVSN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'MYL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NATI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NBL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NCF', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NDE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NDN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NDSN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NDX', 'Close09', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NET', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NEU', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NEWP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NFG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NMG/A', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NOI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NST', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NU', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NXL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'NYB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OCAS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OCR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OGE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OHP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OKE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OLN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ORI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OSG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OSI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'OVER', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PAS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PCH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PCP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PDCO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PDE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PDLI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PETM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PFGI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PHS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PIR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PKG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PKS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PLCM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PLT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PLXS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PMI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PNM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PNR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'POM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'POS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PPE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PPP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PRGO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PRX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PSC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PSD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PSS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PTEN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PWAV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PWR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'PXD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RDA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RDK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RDN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RETK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'REY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RFMD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ROL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'ROST', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RPM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RSAS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RSG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RSLN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'RYN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SCG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SCHL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SCRI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SEIC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SEPR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SFD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SFG', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SII', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SIVB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SJM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SKS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SLAB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SLVN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SMTC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SNDK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SNPS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SON', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SOV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SPW', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SPX', 'Close12', 1
    exec usp_TraderContractStrategy_Import 'US8107', 'SQA/A', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SRCL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SRP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'STE', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'STK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'STR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'STZ', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SUP', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SWFT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SXT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'SY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TBL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TCB', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TDS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TDW', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TECD', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TECUA', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TFX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TOL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TQNT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TRI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TRN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TSAI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TSN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'TTN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'UDR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'UFI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'UHS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'URI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'UTR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'UVV', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VAL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VAR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VARI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VCI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VLO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VRC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VRTX', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VSH', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VVC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'VVI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WABC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WBS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WDR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WEC', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WERN', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WFMI', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WFSL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WFT', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WGL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WGR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WIND', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WL', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WMO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WON', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WPO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WPS', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WR', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WSM', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'WSTC', 'Del-Pre-', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'XRAY', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'XTO', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8107', 'YRK', 'MDYIA', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'AA', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'AXP', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'C', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'CAT', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'CSX', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'CVX', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'CYC', 'CYC', 1
    exec usp_TraderContractStrategy_Import 'US8108', 'DCN', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'DD', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'DE', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'DIS', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'DOT', 'HHHDisp', 1
    exec usp_TraderContractStrategy_Import 'US8108', 'DOW', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'EK', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'ETN', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'F', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'FDX', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'GE', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'GM', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'GP', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'GT', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'HHH', 'HHHDisp', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'HON', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'HPQ', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'IBM', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'IP', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'IR', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'JCI', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'JNJ', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'KO', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'KRI', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MAS', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MCD', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MHS', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MMM', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MO', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MOT', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'MRK', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'OTX', 'OTX', 1
    exec usp_TraderContractStrategy_Import 'US8108', 'PD', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'PG', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'PPG', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'PTV', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'R', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'S', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'T', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'UTX', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'WHR', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'X', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'XOM', 'CYC', 2
    exec usp_TraderContractStrategy_Import 'US8108', 'YHOO', 'HHHDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'AFFX', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'AMGN', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'BBH', 'BBH', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'BGEN', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'BTK', 'BTKDisp', 1
    exec usp_TraderContractStrategy_Import 'US8109', 'CEPH', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'CHIR', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'CRA', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'DNA', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'ENZN', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'GENZ', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'GILD', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'HGSI', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'IDPH', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'IVGN', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'MEDI', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'MLNM', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'PDLI', 'BTKDisp', 2
    exec usp_TraderContractStrategy_Import 'US8109', 'VRTX', 'BTKDisp', 2


    exec usp_IsNewStrategyForUnderlying_Save 1
/* RESULTS ANALYTHING */
IF @@ERROR <> 0 AND @@TRANCOUNT > 0  ROLLBACK TRANSACTION
GO

IF @@TRANCOUNT = 0 BEGIN INSERT INTO #tmpErrors (Error) SELECT 1 BEGIN TRANSACTION END
GO
IF EXISTS (SELECT * FROM #tmpErrors)
BEGIN
	ROLLBACK TRANSACTION
END
GO
IF @@TRANCOUNT > 0 
BEGIN
	select 'Default trader/contract/strategy association insertion succeeded.'
	COMMIT TRANSACTION
END
	ELSE select 'Fail to insert default trader/contract/strategy association.'
GO
DROP TABLE #tmpErrors
GO
