Attribute VB_Name = "basDesign"

Public Const GCOLOR_LABEL_0 = &HCCCCCC
Public Const GCOLOR_LABEL_1 = &HFFFFFF

Public Const GCOLOR_TAB_0 = &H666666
Public Const GCOLOR_TAB_1 = &H333399
Public Const GCOLOR_TAB_2 = &H319ECE    '&H9966&
Public Const GCOLOR_TAB_3 = &H639E31
Public Const GCOLOR_TAB_4 = &H6633CC   'RGB(204, 51, 102)
Public Const GCOLOR_TAB_5 = &H996666

Public Const GCOLOR_BUTTON_BACK = &H8000000F '&HC0C0C0   '&H8000000F '&HAD9A94
Public Const GCOLOR_BUTTON_FORE = &H80000012 '&H0
Public Const GCOLOR_BUTTON_HOVER_BACK = &HF0F0F0  '&HCEBAB5
Public Const GCOLOR_BUTTON_HOVER_FORE = &H80000012 '&H0
Public Const GCOLOR_BUTTON_PRESS_BACK = &HC0FFC0   '&H8CCFFF
Public Const GCOLOR_BUTTON_PRESS_FORE = &H80000012 '&H0
Public Const GCOLOR_BUTTON_DISABLED_BACK = &H8000000F '&HAD9A94
Public Const GCOLOR_BUTTON_DISABLED_FORE = &H808080 '&HCCCCCC

Public Const GCOLOR_RED_ACTIVE_LABEL_FORE = &H66CCFF
Public Const GCOLOR_RED_ACTIVE_LABEL_HOVERFORE = &HBCE7FF
Public Const GCOLOR_RED_ACTIVE_LABEL_PRESSFORE = &H0

Public Const GCOLOR_PROGRESS_BACK = &H8000000C '&H808080   '&H80000010
Public Const GCOLOR_PROGRESS_FORE = &H6633&

Public Const GCOLOR_DIALOGUE_BACK = &H8000000F '&HC0C0C0 '&H8000000F ' &HE7E3E7
Public Const GCOLOR_DIALOGUE_BACK2 = &H8000000F '&HC0C0C0 '&H8000000F '&HF7F3F7

Public Const GCOLOR_TABLE_CAPTION_BACK = GCOLOR_BUTTON_BACK
Public Const GCOLOR_TABLE_CAPTION_FORE = GCOLOR_BUTTON_FORE
'Public Const GCOLOR_TABLE_WHITE_BACK = &HFFFFFF
Public Const GCOLOR_TABLE_WHITE_FORE = &H0
Public Const GCOLOR_TABLE_SELECT_BACK = &HC0FFC0    '&H9CD7F7
Public Const GCOLOR_TABLE_SELECT_FORE = &H0
Public Const GCOLOR_TABLE_SELECT2_BACK = &HC000&       '&H66CCFF
Public Const GCOLOR_TABLE_SELECT2_FORE = &H0
Public Const GCOLOR_TABLE_CHANGED_FORE = vbRed
'Public Const GCOLOR_TABLE_NEW_FORE = vbBlue
Public Const GCOLOR_TABLE_DELETED_FORE = &HC0C0C0
Public Const GCOLOR_TABLE_BACK = &H8000000C '&H808080
Public Const GCOLOR_TABLE_CAPTION_LINE = &H8000000C '&H808080
Public Const GCOLOR_TABLE_LINE = &H8000000F '&HC0C0C0

Public Const GCOLOR_TABLE_NORMAL_FORE = &H80000008
Public Const GCOLOR_TABLE_BAD_FORE = vbRed

Public Enum enmRowsPalette
    RowsPaletteGray
    RowsPaletteRed
    RowsPaletteGreen
    RowsPaletteBlue
End Enum

Public Const GCOLOR_TABLE_ODD_ROW = &HFFFFFF
Public Const GCOLOR_TABLE_EVEN_ROW = &HEEEEEE

Public Const GCOLOR_TABLE_ODD_ROW_GRAY = &HFFFFFF
Public Const GCOLOR_TABLE_EVEN_ROW_GRAY = &HEEEEEE
Public Const GCOLOR_TABLE_ODD_ROW_RED = &HC0C0FF
Public Const GCOLOR_TABLE_EVEN_ROW_RED = &H9999FF
Public Const GCOLOR_TABLE_ODD_ROW_GREEN = &HC0FFFF
Public Const GCOLOR_TABLE_EVEN_ROW_GREEN = &H76C57C
Public Const GCOLOR_TABLE_ODD_ROW_BLUE = &HFFFFC0
Public Const GCOLOR_TABLE_EVEN_ROW_BLUE = &HCCCC99

'Public Const GCOLOR_TABLE_ODD_SUBROW = &HFFFFFF
'Public Const GCOLOR_TABLE_EVEN_SUBROW = &HCCFFFF
'Public Const GCOLOR_TABLE_DISABLED_ROW = &HCCCCCC

Public Const GCOLOR_TABLE_ODD_ROW_EDIT = &HEEFFEE
Public Const GCOLOR_TABLE_EVEN_ROW_EDIT = &HCCEECC

Public Const BKG_COLOR_PRICE_NORMAL = vbWhite
Public Const BKG_COLOR_PRICE_MANUAL = &H80C0FF  ' Red
Public Const BKG_COLOR_PRICE_FEED = &HFFFFC0    ' Blue
Public Const BKG_COLOR_CHILD_WARN = &HC0C0FF    ' Pink
Public Const BKG_COLOR_ROW_CELECTED = &HFFFF&   ' Yellow

