#if !defined(AFX_ACTIONMAP_H__E3067E4D_BDEE_4BD7_A27F_BAA01A53CB56__INCLUDED_)
#define AFX_ACTIONMAP_H__E3067E4D_BDEE_4BD7_A27F_BAA01A53CB56__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CActionMap wrapper class

class AFX_EXT_CLASS CActionMap : public COleDispatchDriver
{
public:
	CActionMap() {}		// Calls COleDispatchDriver default constructor
	CActionMap(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CActionMap(const CActionMap& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetAction();
	void SetAction(long);
	short GetMessage();
	short GetModifier();
	short GetKeycode();
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ACTIONMAP_H__E3067E4D_BDEE_4BD7_A27F_BAA01A53CB56__INCLUDED_)
