#if !defined(AFX_BUBBLE_H__A1DAF0A1_60EF_4F5B_86F5_4285973C193A__INCLUDED_)
#define AFX_BUBBLE_H__A1DAF0A1_60EF_4F5B_86F5_4285973C193A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CBubble wrapper class

class AFX_EXT_CLASS CBubble : public COleDispatchDriver
{
public:
	CBubble() {}		// Calls COleDispatchDriver default constructor
	CBubble(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBubble(const CBubble& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetEncodingMethod();
	void SetEncodingMethod(long);
	double GetMinimumSize();
	void SetMinimumSize(double);
	double GetMaximumSize();
	void SetMaximumSize(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BUBBLE_H__A1DAF0A1_60EF_4F5B_86F5_4285973C193A__INCLUDED_)
