#if !defined(AFX_CANDLE_H__F00BBB83_AAB1_43F1_ACF2_B785F8B2E371__INCLUDED_)
#define AFX_CANDLE_H__F00BBB83_AAB1_43F1_ACF2_B785F8B2E371__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCandle wrapper class

class AFX_EXT_CLASS CCandle : public COleDispatchDriver
{
public:
	CCandle() {}		// Calls COleDispatchDriver default constructor
	CCandle(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCandle(const CCandle& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetIsComplex();
	void SetIsComplex(BOOL);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CANDLE_H__F00BBB83_AAB1_43F1_ACF2_B785F8B2E371__INCLUDED_)
