#if !defined(AFX_DERIVEDSTRING_H__02D44DCA_14C9_4B12_A45E_602E558A0C47__INCLUDED_)
#define AFX_DERIVEDSTRING_H__02D44DCA_14C9_4B12_A45E_602E558A0C47__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDerivedString wrapper class

class AFX_EXT_CLASS CDerivedString : public COleDispatchDriver
{
public:
	CDerivedString() {}		// Calls COleDispatchDriver default constructor
	CDerivedString(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDerivedString(const CDerivedString& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetValue();
	void SetValue(LPCTSTR);
	BOOL GetIsDefault();
	void SetIsDefault(BOOL);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DERIVEDSTRING_H__02D44DCA_14C9_4B12_A45E_602E558A0C47__INCLUDED_)
