#if !defined(AFX_DERIVEDENUM_H__AB82524A_77E7_4BF0_B332_2C988DAF9722__INCLUDED_)
#define AFX_DERIVEDENUM_H__AB82524A_77E7_4BF0_B332_2C988DAF9722__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDerivedEnum wrapper class

class AFX_EXT_CLASS CDerivedEnum : public COleDispatchDriver
{
public:
	CDerivedEnum() {}		// Calls COleDispatchDriver default constructor
	CDerivedEnum(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDerivedEnum(const CDerivedEnum& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetValue();
	void SetValue(short);
	BOOL GetIsDefault();
	void SetIsDefault(BOOL);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DERIVEDENUM_H__AB82524A_77E7_4BF0_B332_2C988DAF9722__INCLUDED_)
