#if !defined(AFX_DERIVEDLONG_H__7F280702_AAD1_428B_9849_9D5621260CB5__INCLUDED_)
#define AFX_DERIVEDLONG_H__7F280702_AAD1_428B_9849_9D5621260CB5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDerivedLong wrapper class

class AFX_EXT_CLASS CDerivedLong : public COleDispatchDriver
{
public:
	CDerivedLong() {}		// Calls COleDispatchDriver default constructor
	CDerivedLong(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDerivedLong(const CDerivedLong& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetValue();
	void SetValue(long);
	BOOL GetIsDefault();
	void SetIsDefault(BOOL);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DERIVEDLONG_H__7F280702_AAD1_428B_9849_9D5621260CB5__INCLUDED_)
