#if !defined(AFX_HILOOPENCLOSE_H__D2E01113_F276_4583_BFB3_A43255E5BD9B__INCLUDED_)
#define AFX_HILOOPENCLOSE_H__D2E01113_F276_4583_BFB3_A43255E5BD9B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHiLoOpenClose wrapper class

class AFX_EXT_CLASS CHiLoOpenClose : public COleDispatchDriver
{
public:
	CHiLoOpenClose() {}		// Calls COleDispatchDriver default constructor
	CHiLoOpenClose(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CHiLoOpenClose(const CHiLoOpenClose& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	BOOL GetIsShowingOpen();
	void SetIsShowingOpen(BOOL);
	BOOL GetIsShowingClose();
	void SetIsShowingClose(BOOL);
	LPDISPATCH GetParent();
	BOOL GetIsOpenCloseFullWidth();
	void SetIsOpenCloseFullWidth(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HILOOPENCLOSE_H__D2E01113_F276_4583_BFB3_A43255E5BD9B__INCLUDED_)
