#if !defined(AFX_LABELCOLLECTION_H__50BA8904_EB49_44C4_9513_2660A7B0D029__INCLUDED_)
#define AFX_LABELCOLLECTION_H__50BA8904_EB49_44C4_9513_2660A7B0D029__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLabel;

/////////////////////////////////////////////////////////////////////////////
// CLabelCollection wrapper class

class AFX_EXT_CLASS CLabelCollection : public COleDispatchDriver
{
public:
	CLabelCollection() {}		// Calls COleDispatchDriver default constructor
	CLabelCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLabelCollection(const CLabelCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	LPDISPATCH GetParent();

// Operations
public:
	CLabel GetItem(const VARIANT& Index);
	void Remove(const VARIANT& Index);
	CLabel Add(LPCTSTR Text, const VARIANT& Before);
	void RemoveAll();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LABELCOLLECTION_H__50BA8904_EB49_44C4_9513_2660A7B0D029__INCLUDED_)
