#if !defined(AFX_LOCATION_H__22731D45_44CA_4194_B76F_48CB869870E3__INCLUDED_)
#define AFX_LOCATION_H__22731D45_44CA_4194_B76F_48CB869870E3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDerivedLong;

/////////////////////////////////////////////////////////////////////////////
// CLocation wrapper class

class AFX_EXT_CLASS CLocation : public COleDispatchDriver
{
public:
	CLocation() {}		// Calls COleDispatchDriver default constructor
	CLocation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLocation(const CLocation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CDerivedLong GetLeft();
	CDerivedLong GetTop();
	CDerivedLong GetWidth();
	CDerivedLong GetHeight();
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LOCATION_H__22731D45_44CA_4194_B76F_48CB869870E3__INCLUDED_)
