#if !defined(AFX_SCIENTIFICVF_H__C507818F_C107_4D6C_A9DA_F4D77381F4C0__INCLUDED_)
#define AFX_SCIENTIFICVF_H__C507818F_C107_4D6C_A9DA_F4D77381F4C0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CScientificVF wrapper class

class AFX_EXT_CLASS CScientificVF : public COleDispatchDriver
{
public:
	CScientificVF() {}		// Calls COleDispatchDriver default constructor
	CScientificVF(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CScientificVF(const CScientificVF& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetDecimalPlaces();
	void SetDecimalPlaces(long);
	BOOL GetUseSmallExponent();
	void SetUseSmallExponent(BOOL);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCIENTIFICVF_H__C507818F_C107_4D6C_A9DA_F4D77381F4C0__INCLUDED_)
