#if !defined(AFX_VALUEFORMAT_H__E1240E72_2102_44F0_9E10_76341BD19471__INCLUDED_)
#define AFX_VALUEFORMAT_H__E1240E72_2102_44F0_9E10_76341BD19471__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CNumberVF;
class CCurrencyVF;
class CAccountingVF;
class CPercentageVF;
class CFractionVF;
class CScientificVF;

/////////////////////////////////////////////////////////////////////////////
// CValueFormat wrapper class

class AFX_EXT_CLASS CValueFormat : public COleDispatchDriver
{
public:
	CValueFormat() {}		// Calls COleDispatchDriver default constructor
	CValueFormat(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CValueFormat(const CValueFormat& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CNumberVF GetNumber();
	void SetNumber(LPDISPATCH);
	CCurrencyVF GetCurrency();
	void SetCurrency(LPDISPATCH);
	CAccountingVF GetAccounting();
	void SetAccounting(LPDISPATCH);
	CPercentageVF GetPercentage();
	void SetPercentage(LPDISPATCH);
	CFractionVF GetFraction();
	void SetFraction(LPDISPATCH);
	CScientificVF GetScientific();
	void SetScientific(LPDISPATCH);
	short GetCategory();
	void SetCategory(short);
	CString GetFormat();
	void SetFormat(LPCTSTR);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VALUEFORMAT_H__E1240E72_2102_44F0_9E10_76341BD19471__INCLUDED_)
