#if !defined(AFX_VALUELABELCOLLECTION_H__8BFC9495_8E1B_4FE7_BD42_AB226C54818C__INCLUDED_)
#define AFX_VALUELABELCOLLECTION_H__8BFC9495_8E1B_4FE7_BD42_AB226C54818C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueLabel;

/////////////////////////////////////////////////////////////////////////////
// CValueLabelCollection wrapper class

class AFX_EXT_CLASS CValueLabelCollection : public COleDispatchDriver
{
public:
	CValueLabelCollection() {}		// Calls COleDispatchDriver default constructor
	CValueLabelCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CValueLabelCollection(const CValueLabelCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetCount();
	LPDISPATCH GetParent();

// Operations
public:
	CValueLabel GetItem(const VARIANT& Index);
	CValueLabel Add(double Value, LPCTSTR Text);
	void Remove(const VARIANT& Index);
	void RemoveAll();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VALUELABELCOLLECTION_H__8BFC9495_8E1B_4FE7_BD42_AB226C54818C__INCLUDED_)
