#if !defined(AFX_VSFLEXDATASOURCE_H__F586F2EE_1A7E_4EBB_8313_EC1393BD1B37__INCLUDED_)
#define AFX_VSFLEXDATASOURCE_H__F586F2EE_1A7E_4EBB_8313_EC1393BD1B37__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVSFlexDataSource wrapper class

class AFX_EXT_CLASS CVSFlexDataSource : public COleDispatchDriver
{
public:
	CVSFlexDataSource() {}		// Calls COleDispatchDriver default constructor
	CVSFlexDataSource(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVSFlexDataSource(const CVSFlexDataSource& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFieldCount();
	long GetRecordCount();
	CString GetFieldName(long Field);
	CString GetData(long Field, long Record);
	void SetData(long Field, long Record, LPCTSTR newData);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VSFLEXDATASOURCE_H__F586F2EE_1A7E_4EBB_8313_EC1393BD1B37__INCLUDED_)
