// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vsflexdatasource.h"


/////////////////////////////////////////////////////////////////////////////
// CVSFlexDataSource properties

/////////////////////////////////////////////////////////////////////////////
// CVSFlexDataSource operations

long CVSFlexDataSource::GetFieldCount()
{
	long result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CVSFlexDataSource::GetRecordCount()
{
	long result;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CVSFlexDataSource::GetFieldName(long Field)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Field);
	return result;
}

CString CVSFlexDataSource::GetData(long Field, long Record)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Field, Record);
	return result;
}

void CVSFlexDataSource::SetData(long Field, long Record, LPCTSTR newData)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Field, Record, newData);
}
