VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsHsGrpAtom"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public ID As Long
Public GroupType As FilterTypeEnum
Public Name As String
    
Public Sub Clear()
    ID = 0
    GroupType = 0
    Name = ""
       
    ClearValues
End Sub

Public Sub ClearValues()
End Sub

Private Sub Class_Initialize()
    On Error Resume Next
    Clear
End Sub
