VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsQnStrikeAtom"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'
'Public Strike As Double
'Private m_aOption(enOtPut To enOtCall) As New clsQnOptAtom
'
'Public Property Get aOption(OptType As Long) As clsQnOptAtom
'    Set aOption = m_aOption(OptType)
'End Property
'
'
