/**
 *	@file	TableIds.h
 *
 *	@brief	Header file for the table ids.
 *
 *	$Log: $
 */

#if !defined(ACTIV_FEED_TABLE_IDS_H)
#define ACTIV_FEED_TABLE_IDS_H

#include "ActivMiddleware/Activ.h"

#include "ActivContentPlatform/ActivFeedCommon/ActivFeedDefinitions.h"


#include <vector>

namespace Activ
{

namespace Feed
{

typedef std::vector<TableNo>  TableNoList;	///<The table number list type definition.

const TableNo TABLE_NO_US_LISTING = 0;
const TableNo TABLE_NO_US_EQUITY_OPTION = 1;
const TableNo TABLE_NO_INDEX = 2;
const TableNo TABLE_NO_US_MARKET_MAKER_QUOTE = 3;
const TableNo TABLE_NO_MARKET_MAKER_QUOTE = 4;
const TableNo TABLE_NO_AMERICAS_LISTING_DEPTH = 5;
const TableNo TABLE_NO_ORDER = 6;
const TableNo TABLE_NO_OPTION = 7;
const TableNo TABLE_NO_US_FUTURE = 16;
const TableNo TABLE_NO_US_FUTURE_OPTION = 17;
const TableNo TABLE_NO_ECN_DEPTH = 19;
const TableNo TABLE_NO_MUTUAL_FUND = 21;
const TableNo TABLE_NO_MONEY_MARKET = 22;
const TableNo TABLE_NO_FUND = 23;
const TableNo TABLE_NO_FOREX = 24;
const TableNo TABLE_NO_OPTION_ROOT = 25;
const TableNo TABLE_NO_OPTION_DELIVERABLE = 26;
const TableNo TABLE_NO_FUTURE_ROOT = 27;
const TableNo TABLE_NO_FUTURE_OPTION_ROOT = 28;
const TableNo TABLE_NO_SYNTHETIC = 29;
const TableNo TABLE_NO_SECURITY = 30;
const TableNo TABLE_NO_COMPANY = 31;
const TableNo TABLE_NO_BANK_COMPANY = 32;
const TableNo TABLE_NO_INDUSTRIAL_COMPANY = 33;
const TableNo TABLE_NO_INSURANCE_COMPANY = 34;
const TableNo TABLE_NO_THRIFT_COMPANY = 35;
const TableNo TABLE_NO_SECTOR = 36;
const TableNo TABLE_NO_EXCHANGE = 37;
const TableNo TABLE_NO_SESSIONS = 38;
const TableNo TABLE_NO_STATISTICS = 39;
const TableNo TABLE_NO_ANALYTICS = 40;
const TableNo TABLE_NO_RANKINGS = 41;
const TableNo TABLE_NO_AMERICAS_FUTURE_DEPTH = 42;
const TableNo TABLE_NO_AMERICAS_OPTION_DEPTH = 43;
const TableNo TABLE_NO_RELATIONSHIP = 100;
const TableNo TABLE_NO_COMPANY_DOMICILE_NAVIGATION = 101;
const TableNo TABLE_NO_FUTURE_OPTION_FUTURE_OPTION_ROOT_NAVIGATION = 102;
const TableNo TABLE_NO_FUTURE_FUTURE_ROOT_NAVIGATION = 103;
const TableNo TABLE_NO_INDEX_CONSTITUENT_NAVIGATION = 104;
const TableNo TABLE_NO_LISTING_SECURITY_NAVIGATION = 105;
const TableNo TABLE_NO_OPTION_ROOT_OPTION_DELIVERABLE_NAVIGATION = 106;
const TableNo TABLE_NO_OPTION_ROOT_UNDERLYING_NAVIGATION = 107;
const TableNo TABLE_NO_SECTOR_CONSTITUENT_NAVIGATION = 108;
const TableNo TABLE_NO_SECURITY_COMPANY_NAVIGATION = 109;
const TableNo TABLE_NO_SYNTHETIC_CONSTITUENT_NAVIGATION = 110;
const TableNo TABLE_NO_LISTING_COMPANY_NAVIGATION = 111;
const TableNo TABLE_NO_ANALYTICS_NAVIGATION = 112;
const TableNo TABLE_NO_PRIMARY_LISTING_NAVIGATION = 113;
const TableNo TABLE_NO_FUTURE_FUTURE_OPTION_EXPIRATION_NAVIGATION = 114;
const TableNo TABLE_NO_CORPORATE_EVENTS = 200;
const TableNo TABLE_NO_DELIST = 201;
const TableNo TABLE_NO_DIVIDEND = 202;
const TableNo TABLE_NO_IPO = 203;
const TableNo TABLE_NO_SPLIT = 204;
const TableNo TABLE_NO_SYMBOL_CHANGE = 205;
const TableNo TABLE_NO_OPTION_SYMBOL_EVENT = 206;
const TableNo TABLE_NO_CUG = 300;
const TableNo TABLE_NO_PERMISSION = 301;
const TableNo TABLE_NO_USER = 302;
const TableNo TABLE_NO_NEWS = 400;
const TableNo TABLE_NO_NEWS_HEADLINE = 401;
const TableNo TABLE_NO_TIME_SERIES_TRADE = 500;
const TableNo TABLE_NO_TIME_SERIES_INTRADAY = 501;
const TableNo TABLE_NO_TIME_SERIES_HISTORY = 502;
const TableNo TABLE_NO_COMPOSITE_EXCHANGE = 503;
const TableNo TABLE_NO_MISCELLANEOUS_ALIAS = 600;
const TableNo TABLE_NO_FUTURE_ALIAS = 601;

/**
 *	@brief	Get table id.
 *
 *	@param	number the table number.
 *	@param	version the table version.
 */
#define ACTIV_FEED_GET_TABLE_ID(number, version)	static_cast<Activ::Feed::TableId>(number | (version << ((sizeof(TableId) * CHAR_BIT) - (1 + 2))))

/**
 *	@brief	Get table number.
 *
 *	@param	id the table id.
 */
#define ACTIV_FEED_GET_TABLE_NUMBER(id)				static_cast<Activ::Feed::TableNo>((id >> ((sizeof(id) * CHAR_BIT) - (3 + 13))) & ((1 << 13) - 1))

/**
 *	@brief	Get table version.
 *
 *	@param	id the table id.
 */
#define ACTIV_FEED_GET_TABLE_VERSION(id)			static_cast<Activ::Feed::TableVersion>((id >> ((sizeof(id) * CHAR_BIT) - (1 + 2))) & ((1 << 2) - 1))

const TableId TABLE_ID_US_LISTING = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_US_LISTING, 0);
const TableId TABLE_ID_US_EQUITY_OPTION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_US_EQUITY_OPTION, 0);
const TableId TABLE_ID_INDEX = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_INDEX, 0);
const TableId TABLE_ID_US_MARKET_MAKER_QUOTE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_US_MARKET_MAKER_QUOTE, 0);
const TableId TABLE_ID_MARKET_MAKER_QUOTE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_MARKET_MAKER_QUOTE, 0);
const TableId TABLE_ID_AMERICAS_LISTING_DEPTH = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_AMERICAS_LISTING_DEPTH, 0);
const TableId TABLE_ID_ORDER = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_ORDER, 0);
const TableId TABLE_ID_OPTION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_OPTION, 0);
const TableId TABLE_ID_US_FUTURE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_US_FUTURE, 0);
const TableId TABLE_ID_US_FUTURE_OPTION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_US_FUTURE_OPTION, 0);
const TableId TABLE_ID_ECN_DEPTH = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_ECN_DEPTH, 0);
const TableId TABLE_ID_MUTUAL_FUND = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_MUTUAL_FUND, 0);
const TableId TABLE_ID_MONEY_MARKET = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_MONEY_MARKET, 0);
const TableId TABLE_ID_FUND = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUND, 0);
const TableId TABLE_ID_FOREX = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FOREX, 0);
const TableId TABLE_ID_OPTION_ROOT = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_OPTION_ROOT, 0);
const TableId TABLE_ID_OPTION_DELIVERABLE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_OPTION_DELIVERABLE, 0);
const TableId TABLE_ID_FUTURE_ROOT = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUTURE_ROOT, 0);
const TableId TABLE_ID_FUTURE_OPTION_ROOT = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUTURE_OPTION_ROOT, 0);
const TableId TABLE_ID_SYNTHETIC = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SYNTHETIC, 0);
const TableId TABLE_ID_SECURITY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SECURITY, 0);
const TableId TABLE_ID_COMPANY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_COMPANY, 0);
const TableId TABLE_ID_BANK_COMPANY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_BANK_COMPANY, 0);
const TableId TABLE_ID_INDUSTRIAL_COMPANY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_INDUSTRIAL_COMPANY, 0);
const TableId TABLE_ID_INSURANCE_COMPANY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_INSURANCE_COMPANY, 0);
const TableId TABLE_ID_THRIFT_COMPANY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_THRIFT_COMPANY, 0);
const TableId TABLE_ID_SECTOR = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SECTOR, 0);
const TableId TABLE_ID_EXCHANGE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_EXCHANGE, 0);
const TableId TABLE_ID_SESSIONS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SESSIONS, 0);
const TableId TABLE_ID_STATISTICS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_STATISTICS, 0);
const TableId TABLE_ID_ANALYTICS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_ANALYTICS, 0);
const TableId TABLE_ID_RANKINGS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_RANKINGS, 0);
const TableId TABLE_ID_AMERICAS_FUTURE_DEPTH = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_AMERICAS_FUTURE_DEPTH, 0);
const TableId TABLE_ID_AMERICAS_OPTION_DEPTH = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_AMERICAS_OPTION_DEPTH, 0);
const TableId TABLE_ID_RELATIONSHIP = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_RELATIONSHIP, 0);
const TableId TABLE_ID_COMPANY_DOMICILE_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_COMPANY_DOMICILE_NAVIGATION, 0);
const TableId TABLE_ID_FUTURE_OPTION_FUTURE_OPTION_ROOT_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUTURE_OPTION_FUTURE_OPTION_ROOT_NAVIGATION, 0);
const TableId TABLE_ID_FUTURE_FUTURE_ROOT_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUTURE_FUTURE_ROOT_NAVIGATION, 0);
const TableId TABLE_ID_INDEX_CONSTITUENT_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_INDEX_CONSTITUENT_NAVIGATION, 0);
const TableId TABLE_ID_LISTING_SECURITY_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_LISTING_SECURITY_NAVIGATION, 0);
const TableId TABLE_ID_OPTION_ROOT_OPTION_DELIVERABLE_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_OPTION_ROOT_OPTION_DELIVERABLE_NAVIGATION, 0);
const TableId TABLE_ID_OPTION_ROOT_UNDERLYING_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_OPTION_ROOT_UNDERLYING_NAVIGATION, 0);
const TableId TABLE_ID_SECTOR_CONSTITUENT_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SECTOR_CONSTITUENT_NAVIGATION, 0);
const TableId TABLE_ID_SECURITY_COMPANY_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SECURITY_COMPANY_NAVIGATION, 0);
const TableId TABLE_ID_SYNTHETIC_CONSTITUENT_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SYNTHETIC_CONSTITUENT_NAVIGATION, 0);
const TableId TABLE_ID_LISTING_COMPANY_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_LISTING_COMPANY_NAVIGATION, 0);
const TableId TABLE_ID_ANALYTICS_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_ANALYTICS_NAVIGATION, 0);
const TableId TABLE_ID_PRIMARY_LISTING_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_PRIMARY_LISTING_NAVIGATION, 0);
const TableId TABLE_ID_FUTURE_FUTURE_OPTION_EXPIRATION_NAVIGATION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUTURE_FUTURE_OPTION_EXPIRATION_NAVIGATION, 0);
const TableId TABLE_ID_CORPORATE_EVENTS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_CORPORATE_EVENTS, 0);
const TableId TABLE_ID_DELIST = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_DELIST, 0);
const TableId TABLE_ID_DIVIDEND = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_DIVIDEND, 0);
const TableId TABLE_ID_IPO = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_IPO, 0);
const TableId TABLE_ID_SPLIT = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SPLIT, 0);
const TableId TABLE_ID_SYMBOL_CHANGE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_SYMBOL_CHANGE, 0);
const TableId TABLE_ID_OPTION_SYMBOL_EVENT = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_OPTION_SYMBOL_EVENT, 0);
const TableId TABLE_ID_CUG = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_CUG, 0);
const TableId TABLE_ID_PERMISSION = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_PERMISSION, 0);
const TableId TABLE_ID_USER = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_USER, 0);
const TableId TABLE_ID_NEWS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_NEWS, 0);
const TableId TABLE_ID_NEWS_HEADLINE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_NEWS_HEADLINE, 0);
const TableId TABLE_ID_TIME_SERIES_TRADE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_TIME_SERIES_TRADE, 0);
const TableId TABLE_ID_TIME_SERIES_INTRADAY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_TIME_SERIES_INTRADAY, 0);
const TableId TABLE_ID_TIME_SERIES_HISTORY = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_TIME_SERIES_HISTORY, 0);
const TableId TABLE_ID_COMPOSITE_EXCHANGE = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_COMPOSITE_EXCHANGE, 0);
const TableId TABLE_ID_MISCELLANEOUS_ALIAS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_MISCELLANEOUS_ALIAS, 0);
const TableId TABLE_ID_FUTURE_ALIAS = ACTIV_FEED_GET_TABLE_ID(TABLE_NO_FUTURE_ALIAS, 0);

} // namespace Feed

} // namespace Activ

#endif // !defined(ACTIV_FEED_TABLE_IDS_H)
